### ISSUE TITLE
Players get stuck when doing the stomp

### ISSUE THREAD

**Issue by teemid** [eirikwah/JumpWaveGame#15]

**Comment by eirikwah** [comment]
I cannot reproduce this. How did you test, @teemid ?

**Comment by teemid** [comment]
When in the arena and jumping the character would get caught in an infinite smash down animation. Seemed like they never reached the collision plane below the arena. They were just floating on top of the arena tiles with alot of down force/gravity.

Might be an issue with physics settings og the arena collision plane?
